### ISSUE TITLE
using dict() on a stix2 object will not correctly serialize datetime properties

### ISSUE THREAD

**Issue by Cyb3rWard0g** [Cyb3rWard0g/ATTACK-Python-Client#2]
This is apparently is a bug in Pandas and not in STIX2 according to this https://github.com/mitre/cti/issues/17 . The suggestion is to apply a workaround:
```
Don't put them in dictionaries and instead serialize them and load the strings back to have a JSON object that you can pass to the pandas
```

**Comment by emmanvg** [comment]
Hi @Cyb3rWard0g, you should read oasis-open/cti-python-stix2#183. You should **not** use `dict()` to serialize a stix2 object and instead use a different approach. Initially I thought that was a bug, but the behavior of dict() is simply different.
